apiVersion: v1
kind: Service
metadata:
  name: eks-inject-webhook-svc
spec:
  selector:
    app: eks-inject-webhook
  ports:
    - protocol: TCP
      port: 443
      targetPort: {{ .Values.service.port }}
