{{- if not .Values.webhook.certificates.autoGenerate }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: eks-inject-webhook
webhooks:
  - name: eks-inject-webhook-svc.default.svc
    clientConfig:
      service:
        name: eks-inject-webhook-svc
        namespace: "{{ .Release.Namespace }}"
        path: "/inject"
      caBundle: {{ .Values.webhook.certificates.caBundle }}
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    namespaceSelector:
      matchLabels:
        mutate-webhook: aws-inject
    rules:
      - operations: ["CREATE"]
        apiGroups: ["*"]
        apiVersions: ["v1"]
        resources: ["deployments", "daemonsets", "configmaps"]
        scope: "*"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
{{ end }}
