{{- if not .Values.webhook.certificates.autoGenerate }}
apiVersion: v1
kind: Secret
metadata:
  name: eks-inject-webhook-certs
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.webhook.certificates.cert }}
  tls.key: {{ .Values.webhook.certificates.key }}
{{ end }}
