apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-injector-sa
  {{- if not .Values.aws.credentials.createCredentials }}
  {{- if .Values.aws.credentials.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.credentials.roleArn }}
  {{- end }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-injector-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-injector-role-binding
subjects:
- kind: ServiceAccount
  name: aws-injector-sa
  namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: ClusterRole
  name: aws-injector-role
  apiGroup: rbac.authorization.k8s.io
