name: "Build"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v3

      - name: Build container
        run: make build-docker
        
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up GO 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true
      
      - name: Run unit tests
        run: make test
